version: '2.3'
services:

  # elasticsearch - Backend NoSQL Baseado em Apache Lucene
  elasticsearch:
    container_name: elasticsearch    
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.2
    environment: 
      - "http.host:0.0.0.0"
      - "transport.host:127.0.0.1"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes: 
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch_data:/usr/share/elasticsearch/data      
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:9200 || exit"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - log

  # kibana - Visualização de Logs - kibana irá apresentar os logs criados no elasticsearch
  kibana:
    container_name: kibana    
    image: docker.elastic.co/kibana/kibana-oss:7.3.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml   
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch

    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:5601 || exit"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment: 
      server.name: kibana
      elasticsearch.hosts: http://elasticsearch:9200


    networks:
      - log
  
volumes:
  mq_data:
  elasticsearch_data:

networks:
  log: # Nome da rede
    driver: bridge # Tipo do Driver de rede
