version: '2.3'
services:

  # rabbitmq - Servidor de Mensageria - Enfileiramento de Logs
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management-alpine
    volumes:
      - mq_data:/var/lib/rabbitmq/mnesia
    ports:
      - "15672:15672"
      - "5672:5672" 
    networks:
      - log
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: 123qwe
      RABBITMQ_DEFAULT_VHOST: DevOps

  # logstash - Pipeline - Estrutura de transporte
  logstash:
    container_name: logstash    
    image: docker.elastic.co/logstash/logstash-oss:7.3.2
    volumes:
      - ./logstash.conf:/config/logstash.conf      
      - /var/run/docker.sock:/var/run/docker.sock:rw
    depends_on:
      - rabbitmq # logstash depende do rabbitmq, pois ele precisa consumir da fila
      - elasticsearch # logstash depende do elasticsearch para gravar os logs no elasticsearch
    links:
      - rabbitmq:AMQPServer
      - elasticsearch:elasticsearch
    networks:
      - log    
    command: ["-f", "/config/logstash.conf"]

  # elasticsearch - Backend NoSQL Baseado em Apache Lucene
  elasticsearch:
    container_name: elasticsearch    
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.3.2
    environment: 
      - "http.host:0.0.0.0"
      - "transport.host:127.0.0.1"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes: 
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - elasticsearch_data:/usr/share/elasticsearch/data      
      - /var/run/docker.sock:/var/run/docker.sock:rw
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:9200 || exit"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - log

  # kibana - Visualização de Logs - kibana irá apresentar os logs criados no elasticsearch
  kibana:
    container_name: kibana    
    image: docker.elastic.co/kibana/kibana-oss:7.3.2
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml   
      - /var/run/docker.sock:/var/run/docker.sock:rw
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"
    links:
      - elasticsearch:elasticsearch

    healthcheck:
      test: ["CMD-SHELL", "curl -I -s -L http://localhost:5601 || exit"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment: 
      server.name: kibana
      elasticsearch.hosts: http://elasticsearch:9200
    networks:
      - log

  # MetricBeat - Monitora servidores coletando métricas do sistema e dos serviços em execução no servidor
  metricbeat:
    container_name: metricbeat
    image: docker.elastic.co/beats/metricbeat:7.3.2
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock:rw
    depends_on:
      kibana:
        condition: service_healthy
    links:
      - kibana:kibana
    networks:
      - log
  
volumes:
  mq_data:
  elasticsearch_data:

networks:
  log: # Nome da rede
    driver: bridge # Tipo do Driver de rede
